# Generated by Django 2.2.10 on 2020-03-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
