# Generated by Django 2.2.10 on 2020-03-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200308_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, default='null', null=True, upload_to='pdfs/'),
        ),
    ]
